version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mood-tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}
